# Generated by Django 5.0 on 2024-01-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insertvalue',
            old_name='image',
            new_name='image1',
        ),
    ]
